apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
  labels:
    app: tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-app
        image: leedowon/myweb:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-tomcat
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
