- name: docker configure
  hosts: local
  tasks:
  - name: docker build and push
    community.docker.docker_image:
      build:
        path: /home/vagrant/myweb_dir
      name: leedowon/myweb
      tag: 1.0
      push: yes
      source: build

- name: kubernetes configure
  hosts: kube
  tasks:
  - name: send manifest to kubeHost
    command: kubectl apply -f manifest.yaml
